linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  govet:
    check-shadowing: true
    enable:
      - fieldalignment
  nolintlint:
    require-explanation: true
    require-specific: true
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - github.com/simplefxn/goircd
          - $gostd
          - github.com/google # all google packages
          - github.com/rs/zerolog
          - github.com/urfave/cli/v2
      test:
        files:
          - "$test"
        allow:
          - github.com/simplefxn/goircd
          - $gostd
          - github.com/stretchr
          - github.com/rs/zerolog
          - github.com/urfave/cli/v2

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exportloopref
    - exhaustive
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gomnd
    - gocyclo
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nolintlint
    - nakedret
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace
    - wsl

run:
  issues-exit-code: 1